{"name": "test_math", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2\n  +3\n  -2", "trace": "self = <testcases.Pytest.test_learn.Testpy object at 0x00000289D96FF948>\n\n    def test_math(self):  # 在类中称为方法，方法命名规则与函数一样，以test_开头\n>       assert 1 + 2 == 2\nE       assert 3 == 2\nE         +3\nE         -2\n\ntest_learn.py:11: AssertionError"}, "start": 1631022301216, "stop": 1631022301217, "uuid": "a64d7804-f7ab-43d9-afdf-c3a47b62e4a8", "historyId": "35a1317dc877dd1c6276f4def4a208c8", "testCaseId": "cc34fc2eaf6d59808bd3c0053c2b0d9a", "fullName": "test_learn.Testpy#test_math", "labels": [{"name": "suite", "value": "test_learn"}, {"name": "subSuite", "value": "Testpy"}, {"name": "host", "value": "DESKTOP-E28U2SJ"}, {"name": "thread", "value": "32832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_learn"}]}